// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5unsHmVtx8ziXr_DAGeqp7p5IO9wZ42g',
    appId: '1:66271824789:ios:e7c357160d2ba07fec049c',
    messagingSenderId: '66271824789',
    projectId: 'akespsfm',
    storageBucket: 'akespsfm.firebasestorage.app',
    iosBundleId: 'com.example.sfm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5unsHmVtx8ziXr_DAGeqp7p5IO9wZ42g',
    appId: '1:66271824789:ios:e7c357160d2ba07fec049c',
    messagingSenderId: '66271824789',
    projectId: 'akespsfm',
    storageBucket: 'akespsfm.firebasestorage.app',
    iosBundleId: 'com.example.sfm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSoghwTNKgLBwRoAy3EJQJdNU-pwQEkGA',
    appId: '1:66271824789:web:85ccd3390abc065bec049c',
    messagingSenderId: '66271824789',
    projectId: 'akespsfm',
    authDomain: 'akespsfm.firebaseapp.com',
    storageBucket: 'akespsfm.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSoghwTNKgLBwRoAy3EJQJdNU-pwQEkGA',
    appId: '1:66271824789:web:85ccd3390abc065bec049c',
    messagingSenderId: '66271824789',
    projectId: 'akespsfm',
    authDomain: 'akespsfm.firebaseapp.com',
    storageBucket: 'akespsfm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrjS-ZgoXjkw3jTESlWj5hjY9hIzmyRnM',
    appId: '1:66271824789:android:550d04c517824a7aec049c',
    messagingSenderId: '66271824789',
    projectId: 'akespsfm',
    storageBucket: 'akespsfm.firebasestorage.app',
  );

}